language: python
python:
- '2.7.13'
- '3.3'
before_install:
- sudo apt-get -qq update
- sudo apt-get install python-pip
- sudo apt-get install python3-pip
install:
- pip install six
- pip install -r hdijupyterutils/requirements.txt -e hdijupyterutils
- pip install -r autovizwidget/requirements.txt -e autovizwidget
- pip install -r sparkmagic/requirements.txt -e sparkmagic
- mkdir ~/.sparkmagic
script:
- nosetests hdijupyterutils
- nosetests autovizwidget
- nosetests sparkmagic
