language: python
python:
- '2.7.13'
- '3.3'
install:
- pip install six
- pip install -r hdijupyterutils/requirements.txt -e hdijupyterutils
- pip install -r autovizwidget/requirements.txt -e autovizwidget
- pip install -r sparkmagic/requirements.txt -e sparkmagic
- mkdir ~/.sparkmagic
script:
- nosetests hdijupyterutils
- nosetests autovizwidget
- nosetests sparkmagic
